name: Publish API docs

on:
  repository_dispatch:
    types: [trigger-worflow]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Publish API docs
        run: |
          echo "Publishing API docs..."
          cd v2
          curl -o api.json https://fipe.parallelum.dev/swagger/doc.json
          docker run --rm -v $PWD:/spec redocly/cli build-docs doc.json -t ./custom.hbs -o index.html

      - name: Display changes
        run: |
          git diff --exit-code || true

      - uses: stefanzweifel/git-auto-commit-action@v5
